name: build_TV

on:
  workflow_dispatch:

jobs:
  build_TV:
    name: Build
    runs-on: ubuntu-18.04
    permissions:
      contents: write
    steps:
      - name: clone
        run: |
            git clone https://github.com/techcaotri/ubuntu-18.04-build-qt6
            
      - name: install_prerequisites
        run: |
           cd ubuntu-18.04-build-qt6/shared_folder
           ./install_prerequisites.sh
      - name: prepare_qt6_sources
        run: |
           cd ubuntu-18.04-build-qt6/shared_folder
           ./prepare_qt6_sources.sh
      - name: build_Qt_6_4_3
        run: |
           cd ubuntu-18.04-build-qt6/shared_folder
           ./build_Qt_6_4_3.sh
      #上传APK至Artifacts
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: |
            simple_live_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-x86_64-release.apk
