name: build_TV

on:
  workflow_dispatch:

jobs:
  build_TV:
    name: Build
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
      - name: clone
        run: |
            apt-get update && \ 
            apt-get install locales sudo net-tools lsb-release software-properties-common gnupg git -y \
            apt-get install apt-utils \
            vim git wget curl locales ssh htop \
            build-essential libssl-dev zlib1g-dev libbz2-dev \
            libreadline-dev libsqlite3-dev wget curl llvm \
            libncurses5-dev libncursesw5-dev xz-utils liblzma-dev \
            libxcb* libgl1-mesa-dev libglu1-mesa-dev  libasound2-dev libpulse-dev libinput-dev libudev-dev libatspi2.0-dev libssl-dev openssl libvulkan-dev \
            g++ make unzip zip -y          
            git clone https://github.com/techcaotri/ubuntu-18.04-build-qt6
            
      - name: install_prerequisites
        run: |
           cd ubuntu-18.04-build-qt6/shared_folder
           ./install_prerequisites.sh
      - name: prepare_qt6_sources
        run: |
           cd ubuntu-18.04-build-qt6/shared_folder
           ./prepare_qt6_sources.sh
      - name: build_Qt_6_4_3
        run: |
           cd ubuntu-18.04-build-qt6/shared_folder
           ./build_Qt_6_4_3.sh
      #上传APK至Artifacts
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: |
            simple_live_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-x86_64-release.apk
