name: cache linuxdeployqt

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:10

    steps:
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - run: apt update && apt install git wget curl gzip -y
      - run: git clone https://github.com/Greatwallcorner/TV-Multiplatform
      - run: chmod +x ./gradlew && ./gradlew createReleaseDistributable
      - run: ./gradlew packageReleaseDistributionForCurrentOS
      - run: tar czvf cache.tar.gz ./.gradle
      
