name: ports flowus

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:10
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
     - run: apt install p7zip-full unzip wget curl -y
     - run: |
        wget https://desktopdownload.flowus.cn/production/windows/x64/FlowUs%20Setup%201.1.7.exe
        7z x *.exe
        rm *.exe
        7z x ./**/app-64.7z
        rm ./**/app-64.7z
     - run: |
        mkdir -p dist/opt/apps/cn.flowus.flowus/files
        mkdir -p dist/DEBIAN
        mkdir -p dist/opt/apps/cn.flowus.flowus/files
        mkdir -p dist/opt/apps/cn.flowus.flowus/entries/applications
        mkdir -p dist/opt/apps/cn.flowus.flowus/entries/icons/hicolor/512x515/apps
     - run: |
        cat << 'EOF' >> dist/opt/apps/cn.flowus.flowus/entries/applications/flowus.desktop
        [Desktop Entry]
        Version=1.0
        Type=Application
        Name=FlowUs
        GenericName=Online Document Editor
        Comment=Your connected workspace for wiki, docs & projects
        Exec=/opt/apps/cn.flowus.flowus/files/flowus %U
        Icon=cn.flowus.flowus
        Categories=Office;
        MimeType=x-scheme-handler/notion;
        EOF
        
        cat << 'EOF' >> dist/DEBIAN/control
        Package: cn.flowus.flowus
        Version: 1.1.7
        Installed-Size: 21000
        Maintainer: kero990 <kero990@qq.com>
        Section: text
        Architecture: <ARCH>
        Priority: optional
        Description: 息流是新一代知识管理与协作平台。该版本由windows版本移植而来。
        EOF
        
        cat << 'EOF' >> dist/opt/apps/cn.flowus.flowus/info 
        {
          "appid": "cn.flowus.flowus",
          "name": "FlowUs",
          "version": "1.1.7",
          "arch": ["<ARCH>"],
          "permissions": {
            "autostart": true,
            "notification": true,
            "trayicon": true,
            "clipboard": true,
            "account": true,
            "bluetooth": true,
            "camera": true,
            "audio_record": true,
            "installed_apps": true
          }
        }
        EOF
        echo "文件创建完成"
        sed -i s@\<ARCH\>@${{ matrix.arch }}@g dist/opt/apps/cn.flowus.flowus/info
        sed -i s@\<ARCH\>@${{ matrix.arch }}@g dist/DEBIAN/control
        echo "arch替换完成"
     - run: |
        if [ "${{ matrix.arch }}" = "arm64" ]; then
            export ARCH="arm64"
        else
            export ARCH="x64"
        fi
        wget https://github.com/electron/electron/releases/download/v22.0.2/electron-v22.0.2-linux-$ARCH.zip
        unzip electron-v22.0.2-linux-$ARCH.zip -d electron
        cp electron/* dist/opt/apps/cn.flowus.flowus/files -r
        rm dist/opt/apps/cn.flowus.flowus/files/resources -r
        cp resources/app/resource/icon.png dist/opt/apps/cn.flowus.flowus/entries/icons/hicolor/512x515/apps/cn.flowus.flowus.png
        mv resources dist/opt/apps/cn.flowus.flowus/files/
        mv dist/opt/apps/cn.flowus.flowus/files/electron dist/opt/apps/cn.flowus.flowus/files/flowus
     - run: |
        dpkg-deb -b dist/
        mv dist.deb cn.flowus.flowus_1.1.7_${{ matrix.arch }}.deb
     - name: Upload artifact
       uses: actions/upload-artifact@v2
       with:
        name: flowus
        path: ./*.deb
     
