name: build_hl

on:
  workflow_dispatch:

jobs:
  build:
      runs-on: windows-2019
      
      steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
