name: Build notion-app-electron

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:10

    steps:
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install -g asar 
        apt update
        apt install p7zip-full icoutils wget unzip -y

    - name: Prepare package
      run: |
        mkdir -p dist
        wget https://desktop-release.notion-static.com/Notion%20Setup%203.7.0.exe
        7z x ./*.exe
        rm ./*.exe
        7z x ./**/app-64.7z
        rm ./**/app-64.7z
        asar e ${{ github.workspace }}/**/app.asar ${{ github.workspace }}/unpacked
        icotool -x -w 256 ${{ github.workspace }}/unpacked/icon.ico -o ${{ github.workspace }}/notion.png
        icotool -x -w 256 ${{ github.workspace }}/resources/trayIcon.ico -o ${{ github.workspace }}/trayIcon.png
        sed -i -e 's/"win32"===process.platform/(true)/g' \
               -e 's/_.Store.getState().app.preferences?.isAutoUpdaterDisabled/(true)/g' \
               -e 's!extra-resources!/usr/share/notion-app!g' \
               -e 's/trayIcon.ico/trayIcon.png/g' ${{ github.workspace }}/unpacked/.webpack/main/index.js
        find ${{ github.workspace }} \( -name "clang-format.js" -or -name "conversion.js" -or -name "eslint-format.js" \) -delete -printf "rm %p to make namcap happy.\n"

    - name: rebuild better-sqlite3
      run: |
        npm install --save better-sqlite3
        npm install --save-dev electron-rebuild
        npm i --save node-mac-window
        node_modules/.bin/electron-rebuild -f -w better-sqlite3

    - name: Package DEB
      run: |
        mkdir -p dist/DEBIAN
        mkdir -p dist/opt/apps/so.notion.notion/files
        mkdir -p dist/opt/apps/so.notion.notion/entries/applications
        mkdir -p dist/opt/apps/so.notion.notion/entries/icons/hicolor/256x256/apps
        
        cat << EOF >> dist/opt/apps/so.notion.notion/files/notion
        #!/usr/bin/bash
        
        XDG_CONFIG_HOME=$HOME/.config
        
        # Allow users to override command-line options
        if [[ -f $HOME/.config/notion-flags.conf ]]; then
            NOTION_USER_FLAGS=""
        fi

        # Launch
        $(dirname "$(readlink -f "$0")")/electron $(dirname "$(readlink -f "$0")")/notion-app  ""
        EOF

        cat << EOF >> dist/opt/apps/so.notion.notion/entries/applications/notion.desktop
        [Desktop Entry]
        Version=1.0
        Type=Application
        Name=Notion
        GenericName=Online Document Editor
        Comment=Your connected workspace for wiki, docs & projects
        Exec=/opt/apps/so.notion.notion/files/notion %U
        Icon=so.notion.notion
        Categories=Office;
        MimeType=x-scheme-handler/notion;
        EOF
        
        cat << EOF >> dist/DEBIAN/control
        Package: so.notion.notion
        Version: 3.7.0
        Installed-Size: 21000
        Maintainer: kero990 <kero990@qq.com>
        Section: text
        Architecture: arm64
        Priority: optional
        Description: notion是享誉全球的著名笔记软件。该版本由windows版本移植而来。
        EOF

        cp -a ${{ github.workspace }}/unpacked/{package.json,node_modules,.webpack} dist/opt/apps/so.notion.notion/files/notion-app
        cp node_modules/better_sqlite3/build/Release/* dist/opt/apps/so.notion.notion/files/notion-app/node_modules/better-sqlite3/build/Release/
        cp node_modules/node-mac-window/build/Release/* dist/opt/apps/so.notion.notion/files/notion-app/node_modules/node-mac-window/build/Release/
        wget https://github.com/electron/electron/releases/download/v29.3.0/electron-v29.3.0-linux-x64.zip
        unzip electron-v29.3.0-linux-x64.zip -d electron
        cp electron/* dist/opt/apps/so.notion.notion/files -r
        find dist -type d -empty -delete

    - name: Create deb package
      run: |
        dpkg-deb -b dist/
        mv dist.deb so.notion.notion_3.7.0_amd.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: notion-app-deb
        path: so.notion.notion_3.7.0_amd.deb
