name: qt for debian10

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:10

    steps:
      - run: apt update
      - run: apt install locales sudo net-tools lsb-release software-properties-common gnupg -y
      - run: apt install apt-utils \
                vim git wget curl locales ssh htop \
                build-essential libssl-dev zlib1g-dev libbz2-dev \
                libreadline-dev libsqlite3-dev wget curl llvm \
                libncurses5-dev libncursesw5-dev xz-utils liblzma-dev \
                g++ make unzip zip -y
      - run: git clone https://github.com/techcaotri/ubuntu-18.04-build-qt6
      - run: cd ubuntu-18.04-build-qt6/shared_folder && ./install_prerequisites.sh
      - run: cd ubuntu-18.04-build-qt6/shared_folder && ./prepare_qt6_sources.sh
      - run: |
          cd ubuntu-18.04-build-qt6/shared_folder
          sed -i s@/home/tripham/Dev/Qt_src/Qt_6.4.3_install@/opt/qt6@g build_Qt_6_4_3.sh
          ./build_Qt_6_4_3.sh
      - name: Upload Packaged Deb to Release
        uses: actions/upload-artifact@v2
        with:
          name: qt6_for_debian10
          path: /opt/qt6/
    
      
          
