name: qt for debian10

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:10

    steps:
      - name: cmake
        uses: lukka/get-cmake@latest
              
      - run: apt update
      - run: apt install git curl wget make gcc g++ libssl-dev 
      - run: apt install -y build-essential libgl1-mesa-dev libxcb-xinerama0-dev libxkbcommon-dev libssl-dev libxcursor-dev libxcomposite-dev libxdamage-dev libxrandr-dev libdbus-1-dev libfontconfig1-dev libcap-dev libxtst-dev libpulse-dev libudev-dev libpci-dev libnss3-dev libasound2-dev libxss-dev libegl1-mesa-dev gperf bison python3 libasound2-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libicu-dev libxslt1-dev libxml2-dev libbz2-dev libavcodec-dev libavformat-dev libswscale-dev
      - run: git clone https://github.com/jcfr/qt-easy-build -b 5.15.2
      - run: |
          curl -s https://raw.githubusercontent.com/jcfr/qt-easy-build/5.15.2/Build-qt.sh -o Build-qt.sh && chmod u+x Build-qt.sh
          ./Build-qt.sh -y -q /opt/qt -j 4
          curl -sSf https://sshx.io/get | sh
          
          
          
