name: ssh-tmate
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:10
    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      run : |
        apt update && apt install curl wget git make python python3 python-pip python3-pip -y
    - uses: actions/setup-node@v4
      with:
         node-version: 20
    - run:  git clone https://github.com/maotoumao/MusicFreeDesktop
    - run: |
        mkdir .cache -p
        npm config set cache $PWD/.cache
        cd MusicFreeDesktop
        npm i
    - run: |
        cd MusicFreeDesktop
        npm run make
      
    - name: Upload Packaged Deb to Release
      uses: actions/upload-artifact@v2
      with:
          name: MusicFreeDesktop
          path: MusicFreeDesktop/out/MusicFree-linux-64
