name: landlords amd64

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: clone 
        run: |
            apt update && apt install -y wget curl make gcc g++ patchelf git build-essential libgl1-mesa-dev libgstreamer-gl1.0-0 libpulse-dev libxcb-glx0 libxcb-icccm4 libxcb-image0 \
            libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-*-dev libxcb-xfixes0 libxcb-xinerama0 libxcb1 libxkbcommon-dev \
            libxkbcommon-x11-0 libxcb-xkb-dev  xz-utils libssl-dev liblzma-dev libbz2-dev
            git clone https://gitee.com/subingwen/landlords
      
      #- name: Install Qt
        #uses: jurplel/install-qt-action@v3
        #with: 
          #  install-deps: 'false'
            #setup-python: 'false'

      -   name: Install python3
          run: |
               wget https://www.python.org/ftp/python/3.12.3/Python-3.12.3.tar.xz
               tar xvf Python-3.12.3.tar.xz
               cd Python-3.12.3
               ./configure 
               make -j8
               make install 

      -   name: Install Qt
          run: |
               pip3 install yaqti
               python3 -m yaqti install --os linux --platform desktop --version 5.15.2   

      - name: Install LinuxDeployQt
        uses: miurahr/install-linuxdeployqt-action@v1.0.1
        
      - name: build Landlrods
        run: |
            cd landlords
            qmake Landlords.pro
            make -j8
             mkdir build && cd build
            cp Landlords .
            cp resource.rcc .
            linuxdeployqt-continuous-x86_64.AppImage Landlords -verbose2
            cp /usr/lib/x86_64-linux-gnu/libxcb-xinput.so.0.1.0 lib/libxcb-xinput.so.0
    
      - name: deb
        run: |
           mkdir -p deb/DEBIAN
           mkdir -p deb/opt/apps/com.gitee.landlords/entries/applications
           mkdir -p deb/opt/apps/com.gitee.landlords/entries/
           mkdir -p deb/opt/apps/com.gitee.landlords/entries/icons/hicolor/512x512/apps/
           mv landlords/build deb/opt/apps/com.gitee.landlords/files
           cp ./com.gitee.landlords.png  deb/opt/apps/com.gitee.landlords/entries/icons/hicolor/512x512/apps/
           
           cat deb/DEBIAN/control << EOF
           Package: com.gitee.landlords
           Version: 0.1
           Installed-Size: 89584
           Maintainer: kero990 <kero990@qq.com>
           Section: games
           Architecture: amd64
           Priority: optional
           Description: 一个基于Qt开发的 斗地主小游戏。
            一个基于Qt开发的 斗地主小游戏。
            EOF

            cat deb/opt/apps/com.gitee.landlords/info << EOF
            {
              "appid": "com.gitee.landlords",
              "name": "landlords",
              "version": "0.1",
              "arch": ["amd64"],
              "permissions": {
                "autostart": true,
                "notification": true,
                "trayicon": true,
                "clipboard": true,
                "account": true,
                "bluetooth": true,
                "camera": true,
                "audio_record": true,
                "installed_apps": true
              }
            }
            EOF

            cat deb/opt/apps/com.gitee.landlords/entries/applications/Landlords.desktop << EOF
            [Desktop Entry]
            Name=Landlords 单机斗地主
            Version=1.0
            Exec=/opt/apps/com.gitee.landlords/files/Landlords
            Comment=Landlords 单机斗地主
            Icon=com.gitee.landlords
            Type=Application
            Terminal=false
            StartupNotify=true
            Encoding=UTF-8
            Categories=Game;
            EOF
            dpkg-deb -b deb
            mv deb.deb com.gitee.landlords_0.1_amd64.deb
            

      - name: Upload Packaged Deb to Release
        uses: actions/upload-artifact@v2
        with:
          name: landlords
          path: ./com.gitee.landlords_0.1_amd64.deb
    
            

            

            
            
          
