name: test arch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [arm64, amd64]
    container:
      image: debian:10

    steps:
    - name: echo info
      run: |
        uname -a
        lsb_release -a
        
