name: test arch

on:
  workflow_dispatch:

jobs:
  build-and-package:
    name: Build and Package
    container:
      image: ${{ matrix.container_image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container_image: ['debian:10', 'arm64v8/debian:10']

    steps:
      

      - name: Check environment
        run: uname -a && lsb_release -a
