name: test arch

on:
  workflow_dispatch:

jobs:
  set_qemu:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU for arm64
        if: matrix.platform == 'arm64'
        uses: docker/setup-qemu-action@v1
  
  build:
    runs-on: ubuntu-latest
    needs: set_qemu
    strategy:
      matrix:
        platform: [amd64, arm64]
    container: ${{ matrix.platform == 'amd64' && 'debian:10' || 'arm64v8/debian:10' }}
    steps:
      - name: Check environment
        run: |
          sudo apt install lsb_release
          uname -a && lsb_release -a
