name: test arch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:10

    steps:
    - name: echo info
      run: |
        uname -a
        lsb_release -a
        
