name: test arch

on:
  workflow_dispatch:

jobs:
  build-and-package:
    name: Build and Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container_image: [debian:10, alpine:latest]
    defaults:
      run:
        shell: bash
        
    steps:
    - name: echo info
      run: |
        uname -a
        lsb_release -a
        
